### ISSUE TITLE
Des noms d'opérateurs sont visibles dans la liste des projets

### ISSUE THREAD

**Issue by Ambrelaoh** [pebble-solutions/App-QSE-controle-frontend#106]
Killian m'a demandé d'ouvrir cette issue.
Antoine voit toujours des opérateurs dans la liste des projets

**Comment by Guillaume35** [comment]
Ce problème n'est pas directement lié à l'application contrôle mais au fait que certains projets portent le nom des agents. Tous les projets actifs se retrouvent dans la liste.
