### ISSUE TITLE
Controle, consultation : Donner la possibilité de rattacher un bouclage à posteriori

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle-frontend#184]
**Description**

Il doit être possible de rattacher un contrôle à un autre contrôle (bouclage) :

- À la clôture du contrôle par le contrôleur : _je boucle le KN 560 du 21 janv. 2023 noté I_
- Par un  responsable niveau 5 lors de la consultation : _le KN 850 boucle le KN 560 du 21 janv. 2023 noté I_

L'API appelée sera _POST /api/v2/collecte/:id/headers_
payload :
```JSON
{
"previous_id": "Number"
}
```
- :id est l'ID de la collecte de bouclage (ex: collecte 150 notée S)
- :previous_id est l'ID de la collecte bouclée (ex : collecte 120 notée I)

**Comment by TigrouForMatic** [comment]
pr feat-bouclageKn 
Front and Back Ok -- finished and tested
--> Deployment  juin -- juillet
