### ISSUE TITLE
Consultation : Ajouter de nouvelles listes

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle-frontend#185]
**Description**

Créer les nouvelles listes suivantes :

- [x] Contrôles non bouclés (important) (ajout d'un formulaire permettant de filtrer par note SAMI)
- -> Tout les controle sans following_id (== null)
- [x] Contrôles non-affectés à un opérateur (important)
- -> Tous donc cible__stricture__personnel_id == null || 0
- [x] Contrôles non-affectés à un contrôleur (important)
--> Tous donc enqueteur__stricture__personnel_id == null || 0
- [x] Grouper par opérateur (important)
- [x] Grouper par contrôleur (important)
- [x] KN de KN (septembre)
- [x] KN non contrôlés (sans Kn² septembre)

**Comment by TigrouForMatic** [comment]
@deathtroll22 : 
Pour la vue src/view/CollecteHeadband.vue

- [ ]  Mettre en place les informations pour qu'elles soient plus lisibles 
- [ ] Prendre plus de place pour les affichées (Ici tout les données sont à droite empactée ou à gauche avec un vide blanc au centre)
- [ ] Supprimer l'affichage des données inutiles --> "Opérateur : " par exemple 
- [ ] Racourcir les données qui ne sont pas essentielles --> Les noms peuvent etre simplifiés : Nans Arnaud -> N. Arnaud ou Nans Ar

**Comment by killiankopp** [comment]
ça me semble complet à première vue
il faut livrer et faire un point avec les utilisateurs

**Comment by TigrouForMatic** [comment]
A déployer
